site_name: IHC - Site do eCAC
site_url: https://interacao-humano-Computador.github.io/2026.1-Grupo01/
repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo01
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/logo_cac.jpeg
  favicon: images/E-cac_icone.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Heatmap:    Planejamento/heatmap.md
    - Sites Selecionados: Planejamento/sites-selecionados.md
    - Site Escolhido: Planejamento/site-escolhido.md
    - Cronograma: Planejamento/cronograma.md
    - Ferramentas: Planejamento/ferramentas.md
    - Processo de design: Planejamento/Processo_de_design.md
    - Agradecimentos: Planejamento/agradecimentos.md

  - Inspeções:
    - Inspeção 1: inspecoes/grupo_1/avaliacao_1.md
    - Inspeção Grupo+1: inspecoes/grupo_+1/avaliacao_1_+1.md
    

  - Atas:
    - Ata 1: Atas/ata_1.md
    - Ata 2: Atas/ata_2.md
    - Ata 3: Atas/ata_3.md
    - Ata 4: Atas/ata_4.md
    - Modelo antigo de Ata: Atas/ata_governo.md
    - Modelo novo de Ata: Atas/ata_modelo_aprender.md

  - Análise de Requisitos:
    - Análise de Documentos: 
      - Análise 1: analise de requisitos/analise_de_documentos/analise_documentos_rafael.md
      - Análise 2: analise de requisitos/analise_de_documentos/analise_documentos_lucas_thiago.md
      - Análise 3: analise de requisitos/analise_de_documentos/analise_documentos_heyttor.md
      - Análise 4: analise de requisitos/analise_de_documentos/analise_documentos_lucas.md
    - Análise de Tarefas: analise de requisitos/Análise de Tarefas/at.md
    - Aspectos Éticos: analise de requisitos/Aspectos Éticos/ae.md
    - Brainstorming:
      - Perfil de Usuário: analise de requisitos/Brainstorming/Reunião/brainstorming.md
      - Planejamento e Resumo do Brainstorming: analise de requisitos/Brainstorming/Roteiro/Brainstorming.md
    - Cenários: analise de requisitos/Cenários/c.md
    - Entrevistas: 
      - Entrevista Heyttor: analise de requisitos/Entrevista/Entrevista_Heyttor.md
      - Roteiro:  analise de requisitos/Entrevista/Roteiro.md
    - Personas: analise de requisitos/Personas/Elenco_de_personas.md
    - Perfil de Usuários: analise de requisitos/Perfil de Usuários/pu.md
    - Agradecimentos: analise de requisitos/agradecimentos.md

  - Apresentações:
    - Apresentações : Apresentações/exemplo.md
  
  - Design-Avaliação-Desenvolvimento:
    - Caracteristicas da plataforma: Design-Avaliação-Desenvolvimento\caracteristicas-da-plataforma\caracteristicas-da-plataforma.md

  - Reuniões:
    - Reunião 1: reunioes/reuniao_1.md
    - Reunião 2: reunioes/reuniao_2.md


  - Verificação:
    - Listas de Verificação:
      - Etapa 2:
        - Perfil de Usuário: verificacao/listas-de-verificacao/etapa2/perfil-de-usuario.md
        - Cenários: verificacao/listas-de-verificacao/etapa2/cenarios.md
        - CTT: verificacao/listas-de-verificacao/etapa2/ctt.md
        - Elenco de Personas: verificacao/listas-de-verificacao/etapa2/elenco-de-personas.md
        - Personas: verificacao/listas-de-verificacao/etapa2/personas.md
        - HTA: verificacao/listas-de-verificacao/etapa2/hta.md
      - Etapa 1: 
        - Modelo da Lista de Verificação (pag1): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag1.png
        - Modelo da Lista de Verificação (pag2): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag2.png
        - Modelo da Lista de Verificação (pag3): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag3.png
        - Modelo da Lista de Verificação (pag4): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag4.png
        - Modelo da Lista de Verificação (pag5): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag5.png
        - Modelo da Lista de Verificação (pag6): verificacao/listas-de-verificacao/etapa1/modelo_inspecao/inspecao_pag6.png

    - grupo 1:
      - Etapa 1:
        - Avaliação 1: verificacao/grupo_1/etapa_1/avaliacao_1.md
        - Avaliação do monitor: verificacao/grupo_1/etapa_1/avaliacao_monitor.md
      - Etapa 2: 
        - Perfil de Usuário: verificacao/grupo_1/etapa_2/perfil-de-usuario.md
        - Cenários: verificacao/grupo_1/etapa_2/cenarios.md
        - CTT: verificacao/grupo_1/etapa_2/ctt.md
        - Elenco de Personas: verificacao/grupo_1/etapa_2/elenco-de-personas.md
        - Personas: verificacao/grupo_1/etapa_2/personas.md
        - HTA: verificacao/grupo_1/etapa_2/hta.md 
      - Etapa 3: 
        - Perfil de Usuário: verificacao/grupo_1/etapa_2/perfil-de-usuario.md
        - Cenários: verificacao/grupo_1/etapa_2/cenarios.md
        - CTT: verificacao/grupo_1/etapa_2/ctt.md
        - Elenco de Personas: verificacao/grupo_1/etapa_2/elenco-de-personas.md
        - Personas: verificacao/grupo_1/etapa_2/personas.md
        - HTA: verificacao/grupo_1/etapa_2/hta.md 

    - Grupo 2: 
      - Etapa 1: verificacao/grupo_2/avaliacao_1_+1.md

    - grupo 7:
      - Etapa 2: 
        - Perfil de Usuário: verificacao/grupo_7/etapa_2/perfil-de-usuario.md
        - Cenários: verificacao/grupo_7/etapa_2/cenarios.md
        - CTT: verificacao/grupo_7/etapa_2/ctt.md
        - Elenco de Personas: verificacao/grupo_7/etapa_2/elenco-de-personas.md
        - Personas: verificacao/grupo_7/etapa_2/personas.md
        - HTA: verificacao/grupo_7/etapa_2/hta.md 
         
      
