site_name: IHC - Site do eCAC
site_url: https://interacao-humano-Computador.github.io/2026.1-Grupo01/
repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo01
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/logo_cac.jpeg
  favicon: images/E-cac_icone.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Heatmap:    Planejamento/heatmap.md
    - Sites Selecionados: Planejamento/sites-selecionados.md
    - Site Escolhido: Planejamento/site-escolhido.md
    - Cronograma: Planejamento/cronograma.md
    - Ferramentas: Planejamento/ferramentas.md
    - Processo de design: Planejamento/Processo_de_design.md
    - Agradecimentos: Planejamento/agradecimentos.md
    

  - Análise de Requisitos:
    - Análise de Tarefas e Cenários: 
      - Análise de Tarefas: analise de requisitos/Análise de Tarefas/at.md
      - Cenários: analise de requisitos/Cenários/c.md
    - Aspectos Éticos: analise de requisitos/Aspectos Éticos/ae.md
    - Personas, e Definição de Perfil de Usuário + suas Técnicas:
      - Perfil de Usuários: analise de requisitos/Perfil de Usuários/pu.md
      - Análise de Documentos: 
        - Análise 1: analise de requisitos/analise_de_documentos/analise_documentos_rafael.md
        - Análise 2: analise de requisitos/analise_de_documentos/analise_documentos_lucas_thiago.md
        - Análise 3: analise de requisitos/analise_de_documentos/analise_documentos_heyttor.md
        - Análise 4: analise de requisitos/analise_de_documentos/analise_documentos_lucas.md
      - Brainstorming:
        - Perfil de Usuário: analise de requisitos/Brainstorming/Reunião/brainstorming.md
        - Planejamento e Resumo do Brainstorming: analise de requisitos/Brainstorming/Roteiro/Brainstorming.md
      - Entrevistas: 
        - Entrevista Heyttor: analise de requisitos/Entrevista/Entrevista_Heyttor.md
        - Roteiro:  analise de requisitos/Entrevista/Roteiro.md
      - Personas: analise de requisitos/Personas/Elenco_de_personas.md
    - Caracteristicas de plataforma: analise de requisitos/caracteristicas_de_plataforma/caracteristicas_de_plataforma.md
    - Guia de estilo: analise de requisitos/guia_de_estilo/guia_de_estilo.md
    - Metas de usabilidade: analise de requisitos/metas_de_usabilidade/metas_de_usabilidade.md
    - Principios gerais de projeto: analise de requisitos/principios_gerais_projeto/principios_gerais_projeto.md
    - Agradecimentos: analise de requisitos/agradecimentos.md

  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento:
          - Planejamento da Avaliação da Análise de Tarefas: Design, Avaliação e Desenvolvimento/nivel 1/análise de tarefas/planejamento_avaliacao.md
          - Planejamento dos Resultados da Análise de Tarefas: Design, Avaliação e Desenvolvimento/nivel 1/análise de tarefas/planejamento_resultados.md
        - Avaliação e Relato dos Resultados: 
          - Análises de Tarefas Elaboradas: Design, Avaliação e Desenvolvimento/nivel_1_relatorio/tarefas/tarefas_entrevista.md
      - Storyboard:
        - Planejamento:
          - Planejamento da Avaliação do Storyboard: Design, Avaliação e Desenvolvimento/nivel 1//Storyboard/planejamento_avaliacao.md
          - Planejamento dos Resultados do Storyboard: Design, Avaliação e Desenvolvimento/nivel 1/Storyboard/planejamento_resultados.md
        - Avaliação e Relato dos Resultados: 
          - Storyboard Elaborados: Design, Avaliação e Desenvolvimento/nivel_1_relatorio/storyboards/storyboard.md
      - Anotações das Entrevistas: 
        - Anotações do João: Design, Avaliação e Desenvolvimento/nivel_1_relatorio/anotações/comentários_joão.md
        - Anotações do Thiago: Design, Avaliação e Desenvolvimento/nivel_1_relatorio/anotações/comentários_thiago.md
      - Gravações de validação:
        - Gravações: Design, Avaliação e Desenvolvimento/nivel_1_relatorio/video_de_validacao/videos_validacao.md
    - Nível 2: 
      - Análise de Tarefas: 
        - Relatório da Análise de Tarefas: Design, Avaliação e Desenvolvimento/nivel 1/análise de tarefas/relatorioanalise.md
      - Storyboard: 
        - Relatório do Storyboard: Design, Avaliação e Desenvolvimento/nivel 2/Storyboard/relatoriostoryboard.md

  - Apresentações:
    - Apresentações : Apresentações/exemplo.md
  
  - Reuniões:
    - Reunião 1: reunioes/reuniao_1.md
    - Reunião 2: reunioes/reuniao_2.md

  - Atas:
    - Ata 1: Atas/ata_1.md
    - Ata 2: Atas/ata_2.md
    - Ata 3: Atas/ata_3.md
    - Ata 4: Atas/ata_4.md
    - Modelo antigo de Ata: Atas/ata_governo.md
    - Modelo novo de Ata: Atas/ata_modelo_aprender.md


  - Verificação:
    - Introdução: verificacao/listas-de-verificacao/Introducao.md
    
    - Listas de Verificação:
      - Etapa 1:
        - Modelo da Lista de Verificação (pag1): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag1.md
        - Modelo da Lista de Verificação (pag2): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag2.md
        - Modelo da Lista de Verificação (pag3): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag3.md
        - Modelo da Lista de Verificação (pag4): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag4.md
        - Modelo da Lista de Verificação (pag5): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag5.md
        - Modelo da Lista de Verificação (pag6): verificacao/listas-de-verificacao/etapa1/modelo_inspecao_pag6.md
      - Etapa 2:
        - Perfil de Usuário: verificacao/listas-de-verificacao/etapa2/perfil-de-usuario.md
        - Cenários: verificacao/listas-de-verificacao/etapa2/cenarios.md
        - CTT: verificacao/listas-de-verificacao/etapa2/ctt.md
        - Elenco de Personas: verificacao/listas-de-verificacao/etapa2/elenco-de-personas.md
        - Personas: verificacao/listas-de-verificacao/etapa2/personas.md
        - HTA: verificacao/listas-de-verificacao/etapa2/hta.md
      - Etapa 3:
        - Guia de Estilo: verificacao/listas-de-verificacao/etapa3/Guia_de_estilo.md
        - Metas de Usabilidade: verificacao/listas-de-verificacao/etapa3/metas_de_usabilidade.md
        - Principios Gerais de Projeto: verificacao/listas-de-verificacao/etapa3/principios_gerais_de_projeto.md
      - Etapa 4:
        - Preparação para avaliação de análise de tarefas: verificacao/listas-de-verificacao/etapa4/preparacao_AT.md
        - Preparação para avaliação de Storyboard: verificacao/listas-de-verificacao/etapa4/preparacao_SB.md
        - Preparação para avaliação dos resultados de analise de tarefas: verificacao/listas-de-verificacao/etapa4/preparacao_resultado_AT.md
        - Preparação para avaliação dos resultados de Storyboard: verificacao/listas-de-verificacao/etapa4/preparacao_resultado_SB.md
    - Grupo 1:
      - Etapa 1:
        - Avaliação 1: verificacao/grupo_1/etapa_1/avaliacao_1.md
        - Avaliação do monitor: verificacao/grupo_1/etapa_1/avaliacao_monitor.md
      - Etapa 2: 
        - Perfil de Usuário: verificacao/grupo_1/etapa_2/perfil-de-usuario.md
        - Cenários: verificacao/grupo_1/etapa_2/cenarios.md
        - CTT: verificacao/grupo_1/etapa_2/ctt.md
        - Elenco de Personas: verificacao/grupo_1/etapa_2/elenco-de-personas.md
        - Personas: verificacao/grupo_1/etapa_2/personas.md
        - HTA: verificacao/grupo_1/etapa_2/hta.md 
      - Etapa 3: 
        - Guia de Estilo: verificacao/grupo_1/etapa_3/guia_de_estilo.md
        - Metas de Usabilidade: verificacao/grupo_1/etapa_3/metas_de_usabilidade.md
        - Principios Gerais de Projeto: verificacao/grupo_1/etapa_3/principios_gerais_projeto.md 
      - Etapa 4:
        - Preparação para avaliação de análise de tarefas: verificacao/grupo_1/etapa_4/planejamento_avaliação_AT.md
        - Preparação para avaliação de Storyboard: verificacao/grupo_1/etapa_4/planejamento_avaliação_SB.md
        - Preparação para avaliação dos resultados de analise de tarefas: verificacao/grupo_1/etapa_4/planejamento_resultado_AT.md
        - Preparação para avaliação dos resultados de Storyboard: verificacao/grupo_1/etapa_4/planejamento_resultado_SB.md

    - Grupo 2: 
      - Etapa 1: verificacao/grupo_2/avaliacao_1_+1.md
      - Etapa 3:
        - Guia de Estilo: verificacao/grupo_2/etapa_3/guia_de_estilo.md
        - Metas de Usabilidade: verificacao/grupo_2/etapa_3/metas_de_usabilidade.md
        - Principios Gerais de Projeto: verificacao/grupo_2/etapa_3/principios_gerais_projeto.md
        - Vídeo da verificação: verificacao/grupo_2/etapa_3/video_da_verificação.md

    - Grupo 7:
      - Etapa 2: 
        - Perfil de Usuário: verificacao/grupo_7/etapa_2/perfil-de-usuario.md
        - Cenários: verificacao/grupo_7/etapa_2/cenarios.md
        - CTT: verificacao/grupo_7/etapa_2/ctt.md
        - Elenco de Personas: verificacao/grupo_7/etapa_2/elenco-de-personas.md
        - Personas: verificacao/grupo_7/etapa_2/personas.md
        - HTA: verificacao/grupo_7/etapa_2/hta.md 
        - Vídeo da verificação: verificacao/grupo_7/etapa_2/video_da_verificação.md
      - Etapa 4:
        - Preparação para avaliação de análise de tarefas: verificacao/grupo_7/etapa_4/planejamento_avaliação_AT.md
        - Preparação para avaliação de Storyboard: verificacao/grupo_7/etapa_4/planejamento_avaliação_SB.md
        - Preparação para avaliação dos resultados de analise de tarefas: verificacao/grupo_7/etapa_4/planejamento_resultado_AT.md
        - Preparação para avaliação dos resultados de Storyboard: verificacao/grupo_7/etapa_4/planejamento_resultado_SB.md
        - Vídeo da verificação: verificacao/grupo_7/etapa_4/video_da_verificação.md
         
      
